version: "3"

tasks:
  fix.lint: cargo clippy --all-targets --all-features --fix --allow-staged
  fix.fmt: cargo fmt
  fix:
    cmds:
      - task: fix.lint
      - task: fix.fmt

  check.test: cargo test --all-features
  check.lint: cargo clippy --all-targets --all-features -- -D warnings
  check.fmt: cargo fmt -- --check
  check:
    cmds:
      - task: check.test
      - task: check.lint
      - task: check.fmt

  _check.uncommitted-changes:
    internal: true
    cmds:
      - "[[ -z $(git status -s) ]]"

  publish:
    requires:
      vars:
        - name: MODE
          enum: [patch, minor, major]
    cmds:
      - task: check
      - task: _check.uncommitted-changes
      - dist build # Sanity check that build works
      - cargo bump {{.MODE}}
      - git add --all
      - git commit -m "Bump version v$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')"
      - git tag "v$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')"
      - git push
      - git push --tags
